definitions:
  CommonError:
    properties:
      message:
        description: |-
          Message of the error
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casatemperatura/controllers
  CommonSuccess:
    properties:
      message:
        description: |-
          Message of the error
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casatemperatura/controllers
  GetTemperature:
    properties:
      data:
        $ref: '#/definitions/Temperature'
      message:
        description: |-
          Message of the response
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casatemperatura/controllers
  GetTemperatures:
    properties:
      data:
        $ref: '#/definitions/Temperatures'
      message:
        description: |-
          Message of the response
          in: string
        type: string
        x-go-name: Message
      status:
        description: |-
          Status of the error
          in: int64
        format: int64
        type: integer
        x-go-name: Status
    type: object
    x-go-package: casatemperatura/controllers
  ReqAddTemperature:
    properties:
      valore:
        description: |-
          Value of the Temperature
          in: float
        format: float
        type: number
        x-go-name: Value
    type: object
    x-go-package: casatemperatura/models
  Temperature:
    properties:
      data_inserimento:
        description: |-
          Timestamp of insert
          in: time
        format: date-time
        type: string
        x-go-name: DateInsert
      id:
        description: |-
          Id of Temperature value
          in: int64
        format: int64
        type: integer
        x-go-name: Id
      valore:
        description: |-
          Value of Temperature
          in: float
        format: float
        type: number
        x-go-name: Value
    type: object
    x-go-package: casatemperatura/models
  Temperatures:
    items:
      $ref: '#/definitions/Temperature'
    type: array
    x-go-package: casatemperatura/models
info:
  title: 'Temperature Api:'
  version: 0.1.1
paths:
  /lasthour:
    get:
      description: Get list of last hour of temperature values .... or the last value
        inserted
      operationId: lastHour
      responses:
        "200":
          description: GetTemperatures
          schema:
            $ref: '#/definitions/GetTemperatures'
        "401":
          description: CommonError
          schema:
            $ref: '#/definitions/CommonError'
      security:
      - apiKey:
        - '[]'
  /temperature:
    post:
      description: Create a new temperature value
      operationId: addTemperature
      responses:
        "200":
          description: GetTemperature
          schema:
            $ref: '#/definitions/GetTemperature'
        "401":
          description: CommonError
          schema:
            $ref: '#/definitions/CommonError'
      security:
      - apiKey:
        - '[]'
  /temperatures:
    get:
      description: Get Temperature list
      operationId: listTemperature
      responses:
        "200":
          description: GetTemperatures
          schema:
            $ref: '#/definitions/GetTemperatures'
        "401":
          description: CommonError
          schema:
            $ref: '#/definitions/CommonError'
      security:
      - apiKey:
        - '[]'
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
